services:
  - type: web
    name: streamapi
    env: node
    repo: https://github.com/BotCoder254/streamapi
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TMDB_API_KEY
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT 
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SITE_URL
        sync: false 